In [ ]:
import os
import pandas as pd
import joblib
import pickle

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

In [ ]:
file1_path= os.path.abspath ('/content/drive/My Drive/INTRO TO AI/players_21.csv')

In [ ]:
file2_path= os.path.abspath ('/content/drive/My Drive/INTRO TO AI/players_22.csv')

In [ ]:
fifa21= pd.read_csv(file1_path)

In [ ]:
fifa22= pd.read_csv(file2_path)

<ipython-input-6-b696dc07adbf>:1: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  fifa22= pd.read_csv(file2_path)

In [ ]:
fifa21df= pd.DataFrame(fifa21)

In [ ]:
#creating a subset of the categorical columns from the dataset
categorical_attributes = fifa21.select_dtypes(include=['object', 'category']).columns
attribute_names = categorical_attributes
attribute_names

Index(['player_url', 'short_name', 'long_name', 'player_positions', 'dob',
       'club_name', 'league_name', 'club_position', 'club_loaned_from',
       'club_joined', 'nationality_name', 'nation_position', 'preferred_foot',
       'work_rate', 'body_type', 'real_face', 'player_tags', 'player_traits',
       'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram',
       'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb',
       'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url',
       'club_flag_url', 'nation_logo_url', 'nation_flag_url'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
#encoding the categorical columns
selected_columns_df = fifa21[attribute_names]
label_encoder = LabelEncoder()
label_encoded = selected_columns_df.apply(lambda x: label_encoder.fit_transform(x))
label_encoded
categorical_attributes = pd.DataFrame(label_encoded)

In [ ]:
label_encoded

,player_url,short_name,long_name,player_positions,dob,club_name,league_name,club_position,club_loaned_from,club_joined,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,270,10059,10302,539,942,238,41,0,278,8,...,59,59,59,110,18,313,494,15,39,7
1,4338,3261,3332,587,391,361,24,13,278,1135,...,66,66,66,104,20,14,557,23,28,127
2,1631,14329,14687,560,1271,240,19,27,278,289,...,96,96,96,104,18,1672,476,12,49,124
3,1978,13007,12964,331,2438,461,17,14,278,888,...,52,52,52,110,20,2019,639,17,49,21
4,2209,8987,9626,10,2229,407,15,19,278,487,...,158,158,158,185,22,2250,1,18,16,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,18180,17684,18137,55,4982,138,6,28,278,1769,...,46,46,46,44,9,18214,222,9,49,32
18940,18308,6680,18648,149,4875,560,6,21,278,1769,...,44,44,44,49,9,18342,247,9,49,32
18941,18311,15978,18041,149,2366,608,6,21,278,1769,...,43,43,43,48,1,18345,201,9,49,32
18942,18770,16799,7152,560,6175,444,14,28,278,1769,...,10,10,10,26,7,18803,440,18,49,54
18943,18787,1950,1985,149,6207,444,14,28,278,1769,...,33,33,33,42,7,18820,440,18,49,54

In [ ]:
#creating a subset of the categorical columns from the dataframe
#selected_columns_df = fifa21df[attribute_names]
#dropping the categorical columns based on theor description on kaggle
fifa21df= fifa21df.drop(selected_columns_df ,axis=1)
fifa21df

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
0,158023,93,93,103500000.0,560000.0,33,170,72,241.0,1.0,...,96,32,35,24,6,11,15,14,8,NaN
1,20801,92,92,63000000.0,220000.0,35,187,83,45.0,1.0,...,95,28,32,24,7,11,15,14,11,NaN
2,188545,91,91,111000000.0,240000.0,31,184,80,21.0,1.0,...,88,35,42,19,15,6,12,8,10,NaN
3,190871,91,91,132000000.0,270000.0,28,175,68,73.0,1.0,...,93,35,30,29,9,9,15,15,11,NaN
4,192985,91,91,129000000.0,370000.0,29,181,70,10.0,1.0,...,91,68,65,53,15,13,5,10,13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,257710,47,52,70000.0,1000.0,21,177,70,112165.0,1.0,...,40,45,56,47,12,13,8,14,6,NaN
18940,257933,47,53,70000.0,1000.0,21,174,68,112540.0,1.0,...,35,43,42,53,8,8,13,14,10,NaN
18941,257936,47,47,45000.0,2000.0,28,185,79,111774.0,1.0,...,35,38,43,45,8,5,11,5,7,NaN
18942,258736,47,67,130000.0,500.0,17,171,58,1920.0,4.0,...,45,18,11,13,11,13,9,9,6,NaN
18943,258760,47,67,130000.0,500.0,17,175,65,1920.0,4.0,...,38,32,44,40,12,10,9,6,8,NaN

In [ ]:
#new dataframe with all values encoded
fifa21df

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
0,158023,93,93,103500000.0,560000.0,33,170,72,241.0,1.0,...,96,32,35,24,6,11,15,14,8,NaN
1,20801,92,92,63000000.0,220000.0,35,187,83,45.0,1.0,...,95,28,32,24,7,11,15,14,11,NaN
2,188545,91,91,111000000.0,240000.0,31,184,80,21.0,1.0,...,88,35,42,19,15,6,12,8,10,NaN
3,190871,91,91,132000000.0,270000.0,28,175,68,73.0,1.0,...,93,35,30,29,9,9,15,15,11,NaN
4,192985,91,91,129000000.0,370000.0,29,181,70,10.0,1.0,...,91,68,65,53,15,13,5,10,13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,257710,47,52,70000.0,1000.0,21,177,70,112165.0,1.0,...,40,45,56,47,12,13,8,14,6,NaN
18940,257933,47,53,70000.0,1000.0,21,174,68,112540.0,1.0,...,35,43,42,53,8,8,13,14,10,NaN
18941,257936,47,47,45000.0,2000.0,28,185,79,111774.0,1.0,...,35,38,43,45,8,5,11,5,7,NaN
18942,258736,47,67,130000.0,500.0,17,171,58,1920.0,4.0,...,45,18,11,13,11,13,9,9,6,NaN
18943,258760,47,67,130000.0,500.0,17,175,65,1920.0,4.0,...,38,32,44,40,12,10,9,6,8,NaN

In [ ]:
#dropping columns with low correlation values
correlations = fifa21df.corrwith(fifa21df['overall'])
correlation_threshold= 0.25
low_corr_columns = correlations.index[correlations < correlation_threshold]
print(low_corr_columns)
fifa21df = fifa21df.drop(columns=low_corr_columns)
fifa21df

Index(['sofifa_id', 'height_cm', 'weight_kg', 'club_team_id', 'league_level',
       'club_jersey_number', 'club_contract_valid_until', 'nationality_id',
       'nation_team_id', 'nation_jersey_number', 'weak_foot', 'pace',
       'movement_acceleration', 'movement_sprint_speed', 'movement_balance',
       'defending_sliding_tackle', 'goalkeeping_diving',
       'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes'],
      dtype='object')

,overall,potential,value_eur,wage_eur,age,skill_moves,international_reputation,release_clause_eur,shooting,passing,...,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,goalkeeping_speed
0,93,93,103500000.0,560000.0,33,4,5,138400000.0,92.0,91.0,...,94,44,40,93,95,75,96,32,35,NaN
1,92,92,63000000.0,220000.0,35,5,5,75900000.0,93.0,81.0,...,93,63,29,95,82,84,95,28,32,NaN
2,91,91,111000000.0,240000.0,31,4,4,132000000.0,91.0,78.0,...,85,81,49,94,79,88,88,35,42,NaN
3,91,91,132000000.0,270000.0,28,5,5,166500000.0,85.0,86.0,...,84,51,36,87,90,92,93,35,30,NaN
4,91,91,129000000.0,370000.0,29,4,4,161000000.0,86.0,93.0,...,91,76,66,88,94,84,91,68,65,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18939,47,52,70000.0,1000.0,21,2,1,57000.0,23.0,26.0,...,23,44,50,25,25,35,40,45,56,NaN
18940,47,53,70000.0,1000.0,21,2,1,72000.0,32.0,49.0,...,29,58,42,32,53,35,35,43,42,NaN
18941,47,47,45000.0,2000.0,28,2,1,47000.0,37.0,49.0,...,34,57,35,48,44,36,35,38,43,NaN
18942,47,67,130000.0,500.0,17,2,1,165000.0,46.0,40.0,...,41,33,11,43,49,50,45,18,11,NaN
18943,47,67,130000.0,500.0,17,2,1,165000.0,40.0,48.0,...,30,40,23,47,47,36,38,32,44,NaN

In [ ]:
# List of individual features to be combined
power_attributes = ['power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots']

# Create a new feature "power_combined" by calculating the mean of the individual features
fifa21df['power_combined'] = fifa21df[power_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa21df['power_combined'] = fifa21df['power_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa21df = fifa21df.drop(power_attributes, axis=1)

In [ ]:
# List of individual features to be combined
mentality_attributes = ['mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure']

# Create a new feature "mentality_combined" by calculating the mean of the individual features
fifa21df['mentality_combined'] = fifa21df[mentality_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa21df['mentality_combined'] = fifa21df['mentality_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa21df = fifa21df.drop(mentality_attributes, axis=1)

In [ ]:
# List of individual features to be combined
skill_attributes = ['skill_moves', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control']

# Create a new feature "skill_combined" by calculating the mean of the individual features
fifa21df['skill_combined'] = fifa21df[skill_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa21df['skill_combined'] = fifa21df['skill_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa21df = fifa21df.drop(skill_attributes, axis=1)

In [ ]:
# List of individual features to be combined
attackikng_attributes = ['attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys']

# Create a new feature "attacking_combined" by calculating the mean of the individual features
fifa21df['attacking_combined'] = fifa21df[attackikng_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa21df['attacking_combined'] = fifa21df['attacking_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa21df = fifa21df.drop(attackikng_attributes, axis=1)

In [ ]:
# List of individual features to be combined
movement_attributes = ['movement_agility', 'movement_reactions']

# Create a new feature "movement_combined" by calculating the mean of the individual features
fifa21df['movement_combined'] = fifa21df[movement_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa21df['movement_combined'] = fifa21df['movement_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa21df = fifa21df.drop(movement_attributes, axis=1)

In [ ]:
# List of individual features to be combined
defending_attributes = ['defending_standing_tackle', 'defending_marking_awareness', 'defending']

# Create a new feature "movement_combined" by calculating the mean of the individual features
fifa21df['defending_combined'] = fifa21df[defending_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa21df['defending_combined'] = fifa21df['defending_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa21df = fifa21df.drop(defending_attributes, axis=1)

In [ ]:
#training the model
y=fifa21df['overall']
x=fifa21df.drop('overall',axis=1)
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18944 entries, 0 to 18943
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   potential                 18944 non-null  int64
 1   value_eur                 18707 non-null  float64
 2   wage_eur                  18719 non-null  float64
 3   age                       18944 non-null  int64
 4   international_reputation  18944 non-null  int64
 5   release_clause_eur        17949 non-null  float64
 6   shooting                  16861 non-null  float64
 7   passing                   16861 non-null  float64
 8   dribbling                 16861 non-null  float64
 9   physic                    16861 non-null  float64
 10  goalkeeping_speed         2083 non-null   float64
 11  power_combined            18944 non-null  float64
 12  mentality_combined        18944 non-null  float64
 13  skill_combined            18944 non-null  float64
 14  attacking_combined        18944 non-null  float64
 15  movement_combined         18944 non-null  float64
 16  defending_combined        18944 non-null  float64
dtypes: float64(14), int64(3)
memory usage: 2.5 MB

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#removing NaNs
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

Xtrain = imputer.fit_transform(Xtrain)
Xtest = imputer.fit_transform(Xtest)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(Xtrain)

In [ ]:
from sklearn.ensemble import VotingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
import xgboost as xgb
from xgboost import XGBRegressor

In [ ]:
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

In [ ]:
rf_regressor.fit(X_train_scaled, Ytrain)

RandomForestRegressor(random_state=42)

In [ ]:
y_pred = rf_regressor.predict(Xtest)

In [ ]:
dt=DecisionTreeRegressor(criterion='absolute_error')

In [ ]:
xgb_regressor = XGBRegressor(n_estimators=100, random_state=42)

In [ ]:
xgb_regressor.fit(X_train_scaled, Ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [ ]:
y_pred = xgb_regressor.predict(Xtest)

In [ ]:
#the ensemble model
voting_regressor = VotingRegressor(estimators=[
    ('decision_tree', dt),
    ('xgboost', xgb_regressor),
    ('random_forest', rf_regressor)
])

In [ ]:
from sklearn.metrics import mean_absolute_error

for model in (dt, rf_regressor, xgb_regressor, voting_regressor):
    model.fit(Xtrain, Ytrain)
    y_pred = model.predict(Xtest)
    print(model.__class__.__name__, "MAE:", mean_absolute_error(Ytest, y_pred))

DecisionTreeRegressor MAE: 0.34943256795988387
RandomForestRegressor MAE: 0.27239904988123537
XGBRegressor MAE: 0.3378847192163737
VotingRegressor MAE: 0.2901931695576507

TRAINING WITH PLAYER_22

In [ ]:
fifa22df= pd.DataFrame(fifa22)

In [ ]:
#creating a subset of the categorical columns from the dataset
categorical_attributes2 = fifa22.select_dtypes(include=['object', 'category']).columns
attribute_names2 = categorical_attributes2
attribute_names2

Index(['player_url', 'short_name', 'long_name', 'player_positions', 'dob',
       'club_name', 'league_name', 'club_position', 'club_loaned_from',
       'club_joined', 'nationality_name', 'nation_position', 'preferred_foot',
       'work_rate', 'body_type', 'real_face', 'player_tags', 'player_traits',
       'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram',
       'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb',
       'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url',
       'club_flag_url', 'nation_logo_url', 'nation_flag_url'],
      dtype='object')

In [ ]:
#encoding the categorical columns
selected_columns_df2 = fifa22[attribute_names2]
label_encoder2 = LabelEncoder()
label_encoded2 = selected_columns_df2.apply(lambda x: label_encoder.fit_transform(x))
label_encoded2
categorical_attributes2 = pd.DataFrame(label_encoded2)

In [ ]:
#creating a subset of the categorical columns from the dataframe
selected_columns_df2 = fifa22df[attribute_names2]
#dropping the categorical columns
fifa22df= fifa22df.drop(selected_columns_df2 ,axis=1)
fifa22df

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
0,158023,93,93,78000000.0,320000.0,34,170,72,73.0,1.0,...,96,20,35,24,6,11,15,14,8,NaN
1,188545,92,92,119500000.0,270000.0,32,185,81,21.0,1.0,...,88,35,42,19,15,6,12,8,10,NaN
2,20801,91,91,45000000.0,270000.0,36,187,83,11.0,1.0,...,95,24,32,24,7,11,15,14,11,NaN
3,190871,91,91,129000000.0,270000.0,29,175,68,73.0,1.0,...,93,35,32,29,9,9,15,15,11,NaN
4,192985,91,91,125500000.0,350000.0,30,181,70,10.0,1.0,...,89,68,65,53,15,13,5,10,13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,47,52,70000.0,1000.0,22,180,64,112541.0,1.0,...,37,38,43,48,6,10,5,15,13,NaN
19235,262040,47,59,110000.0,500.0,19,175,70,445.0,1.0,...,47,37,44,47,11,12,6,8,10,NaN
19236,262760,47,55,100000.0,500.0,21,178,72,111131.0,1.0,...,36,38,44,48,8,6,7,10,6,NaN
19237,262820,47,60,110000.0,500.0,19,173,66,111131.0,1.0,...,47,10,14,11,7,10,7,14,15,NaN
19238,264540,47,60,110000.0,500.0,19,167,61,113040.0,1.0,...,36,33,31,37,8,13,13,9,14,NaN

In [ ]:
#combining the encoded categorical columns with the new dataframe
fifa22df

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
0,158023,93,93,78000000.0,320000.0,34,170,72,73.0,1.0,...,96,20,35,24,6,11,15,14,8,NaN
1,188545,92,92,119500000.0,270000.0,32,185,81,21.0,1.0,...,88,35,42,19,15,6,12,8,10,NaN
2,20801,91,91,45000000.0,270000.0,36,187,83,11.0,1.0,...,95,24,32,24,7,11,15,14,11,NaN
3,190871,91,91,129000000.0,270000.0,29,175,68,73.0,1.0,...,93,35,32,29,9,9,15,15,11,NaN
4,192985,91,91,125500000.0,350000.0,30,181,70,10.0,1.0,...,89,68,65,53,15,13,5,10,13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,47,52,70000.0,1000.0,22,180,64,112541.0,1.0,...,37,38,43,48,6,10,5,15,13,NaN
19235,262040,47,59,110000.0,500.0,19,175,70,445.0,1.0,...,47,37,44,47,11,12,6,8,10,NaN
19236,262760,47,55,100000.0,500.0,21,178,72,111131.0,1.0,...,36,38,44,48,8,6,7,10,6,NaN
19237,262820,47,60,110000.0,500.0,19,173,66,111131.0,1.0,...,47,10,14,11,7,10,7,14,15,NaN
19238,264540,47,60,110000.0,500.0,19,167,61,113040.0,1.0,...,36,33,31,37,8,13,13,9,14,NaN

In [ ]:
#dropping columns with low correlation values
correlations2 = fifa22df.corrwith(fifa22df['overall'])
correlation_threshold2= 0.25
low_corr_columns2 = correlations2.index[correlations2 < correlation_threshold2]
print(low_corr_columns2)
fifa22df = fifa22df.drop(columns=low_corr_columns2)

Index(['sofifa_id', 'height_cm', 'weight_kg', 'club_team_id', 'league_level',
       'club_jersey_number', 'club_contract_valid_until', 'nationality_id',
       'nation_team_id', 'nation_jersey_number', 'weak_foot', 'pace',
       'movement_acceleration', 'movement_sprint_speed', 'movement_balance',
       'defending_sliding_tackle', 'goalkeeping_diving',
       'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes'],
      dtype='object')

In [ ]:
# List of individual features to be combined
power_attributes = ['power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots']

# Create a new feature "power_combined" by calculating the mean of the individual features
fifa22df['power_combined'] = fifa22df[power_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa22df['power_combined'] = fifa22df['power_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa22df = fifa22df.drop(power_attributes, axis=1)

In [ ]:
# List of individual features to be combined
mentality_attributes = ['mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure']

# Create a new feature "mentality_combined" by calculating the mean of the individual features
fifa22df['mentality_combined'] = fifa22df[mentality_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa22df['mentality_combined'] = fifa22df['mentality_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa22df = fifa22df.drop(mentality_attributes, axis=1)

In [ ]:
# List of individual features to be combined
skill_attributes = ['skill_moves', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control']

# Create a new feature "skill_combined" by calculating the mean of the individual features
fifa22df['skill_combined'] = fifa22df[skill_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa22df['skill_combined'] = fifa22df['skill_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa22df = fifa22df.drop(skill_attributes, axis=1)

In [ ]:
# List of individual features to be combined
attackikng_attributes = ['attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys']

# Create a new feature "attacking_combined" by calculating the mean of the individual features
fifa22df['attacking_combined'] = fifa22df[attackikng_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa22df['attacking_combined'] = fifa22df['attacking_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa22df = fifa22df.drop(attackikng_attributes, axis=1)

In [ ]:
# List of individual features to be combined
movement_attributes = ['movement_agility', 'movement_reactions']

# Create a new feature "movement_combined" by calculating the mean of the individual features
fifa22df['movement_combined'] = fifa22df[movement_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa22df['movement_combined'] = fifa22df['movement_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa22df = fifa22df.drop(movement_attributes, axis=1)

In [ ]:
# List of individual features to be combined
defending_attributes = ['defending_standing_tackle', 'defending_marking_awareness', 'defending']

# Create a new feature "movement_combined" by calculating the mean of the individual features
fifa22df['defending_combined'] = fifa22df[defending_attributes].mean(axis=1)

# Replace missing (NaN) values with 0
fifa22df['defending_combined'] = fifa22df['defending_combined'].fillna(0)


# Now, you can drop the individual features if needed
fifa22df = fifa22df.drop(defending_attributes, axis=1)

In [ ]:
fifa22df

,overall,potential,value_eur,wage_eur,age,international_reputation,release_clause_eur,shooting,passing,dribbling,physic,goalkeeping_speed,power_combined,mentality_combined,skill_combined,attacking_combined,movement_combined,defending_combined
0,93,93,78000000.0,320000.0,34,5,144300000.0,92.0,91.0,95.0,65.0,NaN,77.8,73.833333,79.000000,85.8,92.5,29.666667
1,92,92,119500000.0,270000.0,32,5,197200000.0,92.0,79.0,86.0,82.0,NaN,84.8,80.666667,68.500000,86.0,85.0,40.333333
2,91,91,45000000.0,270000.0,36,5,83300000.0,94.0,80.0,88.0,75.0,NaN,87.2,74.333333,70.500000,87.6,90.0,30.000000
3,91,91,129000000.0,270000.0,29,5,238700000.0,83.0,86.0,94.0,63.0,NaN,71.8,77.000000,75.166667,80.6,92.5,34.666667
4,91,91,125500000.0,350000.0,30,4,232200000.0,86.0,93.0,88.0,78.0,NaN,81.6,82.666667,74.000000,81.4,85.0,65.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,47,52,70000.0,1000.0,22,1,114000.0,35.0,46.0,48.0,49.0,NaN,47.0,42.333333,35.833333,41.2,54.0,41.000000
19235,47,59,110000.0,500.0,19,1,193000.0,39.0,50.0,46.0,51.0,NaN,48.8,46.500000,36.500000,43.2,56.5,40.666667
19236,47,55,100000.0,500.0,21,1,175000.0,37.0,45.0,49.0,52.0,NaN,49.4,42.500000,36.833333,40.0,52.0,41.000000
19237,47,60,110000.0,500.0,19,1,239000.0,46.0,36.0,48.0,42.0,NaN,45.8,38.500000,32.000000,38.0,60.0,13.000000
19238,47,60,110000.0,500.0,19,1,217000.0,38.0,45.0,48.0,48.0,NaN,49.0,43.500000,34.500000,40.8,59.5,33.333333

In [ ]:
#testing the model with the players_22 data
y1=fifa22df['overall']
x1=fifa22df.drop('overall',axis=1)
x1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19239 entries, 0 to 19238
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   potential                 19239 non-null  int64
 1   value_eur                 19165 non-null  float64
 2   wage_eur                  19178 non-null  float64
 3   age                       19239 non-null  int64
 4   international_reputation  19239 non-null  int64
 5   release_clause_eur        18063 non-null  float64
 6   shooting                  17107 non-null  float64
 7   passing                   17107 non-null  float64
 8   dribbling                 17107 non-null  float64
 9   physic                    17107 non-null  float64
 10  goalkeeping_speed         2132 non-null   float64
 11  power_combined            19239 non-null  float64
 12  mentality_combined        19239 non-null  float64
 13  skill_combined            19239 non-null  float64
 14  attacking_combined        19239 non-null  float64
 15  movement_combined         19239 non-null  float64
 16  defending_combined        19239 non-null  float64
dtypes: float64(14), int64(3)
memory usage: 2.5 MB

In [ ]:
Xtrain2,Xtest2,Ytrain2,Ytest2=train_test_split(x1,y1,test_size=0.2,random_state=42)

In [ ]:
#removing NaNs
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

Xtrain2 = imputer.fit_transform(Xtrain2)
Xtest2 = imputer.fit_transform(Xtest2)

In [ ]:
scaler = StandardScaler()
X2_train_scaled = scaler.fit_transform(Xtrain2)

In [ ]:
ypred = voting_regressor.predict(Xtest2)

In [ ]:
mae = mean_absolute_error(Ytest2, ypred)
mae

0.5325310653956169

In [56]:
joblib.dump(scaler, '/content/drive/My Drive/scaler_ensemble.pkl')

['/content/drive/My Drive/scaler_ensemble.pkl']

In [57]:
import pickle

In [60]:
filename= '/content/drive/My Drive/ensemble_model.pkl'
pickle.dump(voting_regressor, open(filename, 'wb'))
loaded_model= pickle.load(open(filename, 'rb'))

joblib.dump(scaler,'/content/drive/My Drive/INTRO TO AI/players_21.csv'/scaler.pkl')

filename = '/content/drive/My Drive/INTRO TO AI/players_21.csv'/model.pkl'
pickle.dump(voting_regressor,open(filename, 'wb'))
loaded_model = pickle.load(open(filename, 'rb'))